spring:
  datasource:
    url: jdbc:mysql://localhost:3306/face
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


path:
  directorName: C:\Users\Administrator\Desktop


server:
  port: 8888
